"""create wiki tables

Revision ID: 09e9c855fc81
Revises: f17a3f667ae2
Create Date: 2026-06-06 14:54:52.927316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e9c855fc81'
down_revision: Union[str, Sequence[str], None] = 'f17a3f667ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['wiki_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_categories_slug'), 'wiki_categories', ['slug'], unique=True)
    op.create_table('wiki_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_tags_slug'), 'wiki_tags', ['slug'], unique=True)
    op.create_table('wiki_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['wiki_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_pages_author_user_id'), 'wiki_pages', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_wiki_pages_category_id'), 'wiki_pages', ['category_id'], unique=False)
    op.create_index(op.f('ix_wiki_pages_deleted_at'), 'wiki_pages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_wiki_pages_slug'), 'wiki_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_wiki_pages_status'), 'wiki_pages', ['status'], unique=False)
    op.create_table('wiki_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_attachments_page_id'), 'wiki_attachments', ['page_id'], unique=False)
    op.create_index(op.f('ix_wiki_attachments_uploaded_by_user_id'), 'wiki_attachments', ['uploaded_by_user_id'], unique=False)
    op.create_table('wiki_page_tags',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['wiki_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', 'tag_id')
    )
    op.create_table('wiki_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'version_number', name='uq_wiki_versions_page_version')
    )
    op.create_index(op.f('ix_wiki_versions_created_by_user_id'), 'wiki_versions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_wiki_versions_page_id'), 'wiki_versions', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wiki_versions_page_id'), table_name='wiki_versions')
    op.drop_index(op.f('ix_wiki_versions_created_by_user_id'), table_name='wiki_versions')
    op.drop_table('wiki_versions')
    op.drop_table('wiki_page_tags')
    op.drop_index(op.f('ix_wiki_attachments_uploaded_by_user_id'), table_name='wiki_attachments')
    op.drop_index(op.f('ix_wiki_attachments_page_id'), table_name='wiki_attachments')
    op.drop_table('wiki_attachments')
    op.drop_index(op.f('ix_wiki_pages_status'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_slug'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_deleted_at'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_category_id'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_author_user_id'), table_name='wiki_pages')
    op.drop_table('wiki_pages')
    op.drop_index(op.f('ix_wiki_tags_slug'), table_name='wiki_tags')
    op.drop_table('wiki_tags')
    op.drop_index(op.f('ix_wiki_categories_slug'), table_name='wiki_categories')
    op.drop_table('wiki_categories')
    # ### end Alembic commands ###
